export enum CacheEntityName {
  availableWorkers = 'availableWorkers',
  caseCategory = 'caseCategory',
  certification = 'certification',
  closeReason = 'closeReason',
  consent = 'consent',
  department = 'department',
  departmentFunction = 'departmentFunction',
  employmentType = 'employmentType',
  featureConfiguration = 'featureConfiguration',
  jobRole = 'jobRole',
  language = 'language',
  level = 'level',
  permission = 'permission',
  rate = 'rate',
  role = 'role',
  sector = 'sector',
  serviceType = 'serviceType',
  shift = 'shift',
  status = 'status',
  type = 'type',
  workType = 'workType',
}
