export enum MyColleaguesFormFieldName {
  Email = 'email',
  FirstName = 'firstName',
  LastName = 'lastName',
  Title = 'title',
  Department = 'department',
  Function = 'function',
  MainLocation = 'mainLocation',
  ChangeMainLocation = 'changeMainLocation',
  AddressLine1 = 'addressLine1',
  AddressLine2 = 'addressLine2',
  City = 'city',
  State = 'state',
  PostalCode = 'postalCode',
  Country = 'country',
  Permissions = 'permissions',
  PermissionsNote = 'permissionsNote',
  Locations = 'locations',
  LocationsNote = 'locationsNote',
  LocationsCounter = 'locationsCounter',
}
